### ISSUE TITLE
Change body back to expr

### ISSUE THREAD

**Issue by LoganDark** [JENebel/const_for#1]
`=> unsafe { ... }`

You could also use `stmt`

**Comment by JENebel** [comment]
Are you suggesting allowing the following? I guess there would be no reason not to.

`
    const_for!(i in 0..25 => unsafe {
        a += 1
    })
`
`
    const_for(i in 0..25 => i += 1)
`

I will update the crate later today

**Comment by JENebel** [comment]
I have published a new version now, that also includes some bug fixes i found (:
